apiVersion: v1
kind: Secret
metadata: 
  namespace: three-tier
  name: db-secret
type: Opaque
data:  
  username: YWRtaW4=               # admin
  password: U3Ryb25nUGFzc3dvcmQxMjM= # StrongPassword123 (base64)
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: three-tier
spec:
  selector:
    app: mongodb
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017          # Service port (used by backend)
      targetPort: 27017    # MongoDB container port
  type: ClusterIP         # Internal service only
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: three-tier
  name: mongodb
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels: 
        app: mongodb
    spec: 
      containers:
      - name: mongo-cont
        image: mongo:4.4.6
        ports:
        - containerPort: 27017
        env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        hostPath:
          path: /customdbsolution
